"""Render the three cloud-init seed files that go on a Pi's boot partition.

GROUND TRUTH (verified 2026-08-28 by extracting the official image
`2026-06-18-raspios-trixie-arm64-lite.img.xz`, sha256 e235fd24...c33a9, and
reading `/etc/cloud/cloud.cfg` and `/etc/cloud/cloud.cfg.d/99_raspberry-pi.cfg`
out of its root filesystem):

  * Raspberry Pi OS trixie configures cloud-init with
    `datasource_list: [ NoCloud, None ]` and `seedfrom: file:///boot/firmware`.
    So the seed files are `user-data`, `network-config` and `meta-data`, sitting
    in the root of the FAT32 `bootfs` partition - the one Windows mounts.
  * This is NOT the old `custom.toml` mechanism and NOT `firstrun.sh`. Guidance
    written for Bookworm and earlier will tell you otherwise; it is out of date.
    The image's own `os_list_imagingutility_v4.json` entry declares
    `init_format = "cloudinit-rpi"`, which is the machine-readable version of
    this same fact.
  * The default user is `pi` with `lock_passwd: true` and NOPASSWD sudo. It is
    created BY cloud-init, not baked into the image - so a `users:` block that
    omits `default` means the `pi` user is never created at all. That is how
    this module removes it: by never asking for it.
  * `preserve_hostname: false`, so `hostname:` in user-data is honoured.
  * Host keys are generated by `regenerate_ssh_host_keys.service` on first boot
    (`ssh_genkeytypes: []`, `ssh_deletekeys: false`), so flashing the same image
    to five cards does NOT give five Pis the same host key.
  * `meta-data.instance_id` is compared against a cached copy; changing it makes
    cloud-init believe it is on a new instance and re-run first-boot setup. Each
    node therefore gets its own instance_id, stamped with the plan revision.
  * Network renderers are `['netplan', 'network-manager']`, so `network-config`
    is netplan v2 and gets applied through NetworkManager.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path

from .fleet import Fleet, Node

try:  # optional - used only to prove what we emit parses back
    import yaml as _yaml
except ImportError:  # pragma: no cover
    _yaml = None


class BootConfigError(RuntimeError):
    pass


@dataclass
class RoleBundle:
    """Everything the selected roles contribute to one node's first boot."""

    packages: list[str] = field(default_factory=list)
    write_files: list[tuple[str, str, str]] = field(default_factory=list)  # path, content, mode
    runcmd: list[str] = field(default_factory=list)
    summary: str = ""


# --- YAML emission ---------------------------------------------------------------
# Hand-rolled rather than PyYAML, for two reasons: the output stays commented and
# diff-friendly (these files get read by a human at 1am with a card reader in one
# hand), and the wizard keeps its stdlib-only footprint. PyYAML, when present, is
# used to prove the result parses - see validate().


def _q(value: str) -> str:
    """Quote a scalar for YAML. Always quotes, so nothing is ever reinterpreted
    as a bool, a number, a date, or None - the classic YAML foot-guns."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _block(content: str, indent: int) -> str:
    """A literal block scalar, indented. Trailing whitespace is stripped per line
    because YAML block scalars preserve it and shells do not appreciate it."""
    pad = " " * indent
    lines = [pad + line.rstrip() for line in content.splitlines()]
    return "\n".join(lines)


def instance_id(node: Node, plan_revision: str = "") -> str:
    """Stable per node, but changes when the plan changes.

    Deliberate: re-running the wizard after editing fleet.toml should make
    cloud-init treat the card as a new instance and redo first-boot setup,
    rather than silently no-op because it has seen `rpios-image` before.
    """
    digest = hashlib.sha256(
        f"{node.hostname}|{node.ip}|{','.join(sorted(node.roles))}|{plan_revision}".encode()
    ).hexdigest()[:12]
    return f"pi-rack-{node.hostname}-{digest}"


def render_meta_data(node: Node, plan_revision: str = "") -> str:
    iid = instance_id(node, plan_revision)
    return f"""# cloud-init meta-data - generated by piwiz, do not hand-edit.
# Node: {node.hostname} ({node.hardware}) at {node.ip}
#
# dsmode: local means user-data is acted on BEFORE the network comes up, which
# is what we want - the network config itself is part of the seed.
dsmode: local

# BOTH spellings on purpose. cloud-init's canonical NoCloud key is `instance-id`
# (hyphen) and that is what Raspberry Pi Imager writes; the meta-data shipped
# inside the Raspberry Pi OS image spells it `instance_id` (underscore). Rather
# than bet on which one is read, emit both with the same value - the unused one
# is ignored, and there is no version of this where we get the wrong id.
#
# Changing it makes cloud-init treat this as a brand new machine and re-run
# first-boot setup. It is derived from the node's plan entry, so editing
# fleet.toml and re-flashing genuinely re-provisions instead of silently no-oping.
instance-id: {iid}
instance_id: {iid}

# Used for the hostname when no `hostname:` is set in user-data. We always set
# one, but this keeps the two consistent if user-data is ever trimmed.
local-hostname: {node.hostname}
"""


def render_network_config(fleet: Fleet, node: Node) -> str:
    """Static IPv4 on eth0, netplan v2.

    `optional: false` is deliberate and load-bearing: it makes systemd wait for
    the link before cloud-init's later stages run. Every node here installs
    packages on first boot, and on a fast Pi 5 cloud-init will otherwise start
    apt before the link is up and fail the whole run.
    """
    dns = ", ".join(fleet.network.dns)
    prefix = fleet.network.cidr.prefixlen
    return f"""# cloud-init network-config (netplan v2) - generated by piwiz.
# Node: {node.hostname} -> {node.ip}/{prefix}
#
# Whitespace-sensitive YAML. Spaces only, never tabs.
#
# This is applied ONCE, on first boot. Changing it later means either
# re-flashing or editing /etc/netplan on the running node.
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      # false = boot waits for this link. Required: first boot installs packages.
      optional: false
      addresses:
        - {node.ip}/{prefix}
      routes:
        - to: default
          via: {fleet.network.gateway}
      nameservers:
        addresses: [{dns}]
        search: [{fleet.network.domain}]
"""


def render_user_data(
    fleet: Fleet,
    node: Node,
    bundle: RoleBundle | None = None,
    *,
    package_upgrade: bool = False,
) -> str:
    bundle = bundle or RoleBundle()

    pubkey = fleet.ssh_pubkey_path.read_text(encoding="utf-8").strip()
    # Order matters: pointing at the private key instead of the .pub is the
    # common mistake, so it has to be checked before the generic shape test -
    # otherwise it is reported as "not a public key", which is true but unhelpful.
    if "PRIVATE KEY" in pubkey.upper():
        raise BootConfigError(
            f"{fleet.ssh_pubkey_path} is a PRIVATE key. "
            f"Point ssh_pubkey_path at {fleet.ssh_pubkey_path}.pub instead - and "
            "note that this private key has now been read by a tool, so consider "
            "whether it belongs somewhere more protected."
        )
    if not pubkey.startswith(("ssh-ed25519", "ssh-rsa", "ecdsa-sha2")):
        raise BootConfigError(
            f"{fleet.ssh_pubkey_path} does not look like an SSH public key "
            "(expected a line starting ssh-ed25519, ssh-rsa or ecdsa-sha2)"
        )

    packages = sorted(set(BASE_PACKAGES + list(bundle.packages)))

    out: list[str] = []
    add = out.append

    add("#cloud-config")
    add("# Generated by piwiz - do not hand-edit; edit fleet.toml and re-render.")
    add(f"# Node: {node.hostname}  {node.hardware}  {node.ip}")
    add(f"# Roles: {', '.join(node.roles) or '(none)'}")
    if bundle.summary:
        for line in bundle.summary.splitlines():
            add(f"# {line}")
    add("")

    add(f"hostname: {node.hostname}")
    add("prefer_fqdn_over_hostname: false")
    add("manage_etc_hosts: true")
    add("")

    add(f"timezone: {fleet.timezone}")
    add(f"locale: {fleet.locale}")
    add("keyboard:")
    add(f"  layout: {fleet.keyboard}")
    add("")

    add("# No `- default` entry here, and that is the point: on Raspberry Pi OS the")
    add("# `pi` user is created BY cloud-init from system_info.default_user. Omitting")
    add("# `default` means it is never created, so there is no stock account to attack.")
    add("users:")
    add(f"  - name: {fleet.admin_user}")
    add("    gecos: pi-rack admin")
    add("    shell: /bin/bash")
    add("    sudo: \"ALL=(ALL) NOPASSWD:ALL\"")
    add("    groups: [adm, dialout, cdrom, audio, users, sudo, video, games, plugdev, input, gpio, spi, i2c, netdev, render]")
    add("    # No password at all. The only way in is the key below.")
    add("    lock_passwd: true")
    add("    ssh_authorized_keys:")
    add(f"      - {_q(pubkey)}")
    add("")

    add("# Key-only SSH. Combined with lock_passwd above there is no password path in.")
    add("ssh_pwauth: false")
    add("disable_root: true")
    add("")

    add("package_update: true")
    add(f"package_upgrade: {'true' if package_upgrade else 'false'}")
    if package_upgrade:
        add("# NOTE: a full upgrade on first boot can add 5-15 minutes before the node")
        add("#       is reachable, and on a slow card it looks exactly like a failed flash.")
    add("packages:")
    for pkg in packages:
        add(f"  - {pkg}")
    add("")

    files = list(BASE_WRITE_FILES) + list(bundle.write_files)
    if files:
        add("write_files:")
        for path, content, mode in files:
            add(f"  - path: {path}")
            add(f"    permissions: {_q(mode)}")
            add("    owner: root:root")
            add("    content: |")
            add(_block(content, 6))
        add("")

    runcmd = list(bundle.runcmd) + list(BASE_RUNCMD)
    if runcmd:
        add("runcmd:")
        for cmd in runcmd:
            add(f"  - {cmd}")
        add("")

    add(f"final_message: \"pi-rack: {node.hostname} up after $UPTIME seconds, cloud-init $VERSION\"")
    add("")

    return "\n".join(out)


# Installed on every node regardless of role. Kept short on purpose: anything
# role-specific belongs in that role, not here.
BASE_PACKAGES = [
    "avahi-daemon",        # so `<hostname>.local` resolves before DNS is sorted out
    "ca-certificates",
    "chrony",              # accurate clock; a Pi has no RTC and cert checks care
    "curl",
    "git",
    "htop",
    "jq",
    "unattended-upgrades",
    "vim-tiny",
]

BASE_WRITE_FILES: list[tuple[str, str, str]] = [
    (
        "/etc/apt/apt.conf.d/20auto-upgrades",
        "# Enables the timers. On its own this does almost nothing - what actually\n"
        "# gets upgraded is decided by the Origins-Pattern in 51pi-rack-unattended.\n"
        'APT::Periodic::Update-Package-Lists "1";\n'
        'APT::Periodic::Unattended-Upgrade "1";\n'
        'APT::Periodic::AutocleanInterval "7";\n',
        "0644",
    ),
    (
        "/etc/apt/apt.conf.d/51pi-rack-unattended",
        "// Written by piwiz. Numbered 51 so it wins over the shipped 50 file.\n"
        "//\n"
        "// The trap this exists to avoid: a Debian-security-only Origins-Pattern\n"
        "// updates essentially NOTHING on Raspberry Pi OS, because the packages\n"
        "// come from the Raspberry Pi archives, not from Debian's security suite.\n"
        "// A node can look fully patched and be receiving no updates at all.\n"
        "Unattended-Upgrade::Origins-Pattern {\n"
        '        "origin=Debian,codename=${distro_codename},label=Debian-Security";\n'
        '        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";\n'
        '        "origin=Raspbian,codename=${distro_codename},label=Raspbian";\n'
        '        "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation";\n'
        "};\n"
        "\n"
        "// Reboot when a kernel update needs it. Naming a time WITHOUT this switch\n"
        "// - the common mistake - means the node never reboots and quietly runs the\n"
        "// old kernel forever.\n"
        'Unattended-Upgrade::Automatic-Reboot "true";\n'
        'Unattended-Upgrade::Automatic-Reboot-WithUsers "false";\n'
        'Unattended-Upgrade::Automatic-Reboot-Time "04:30";\n'
        'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";\n'
        'Unattended-Upgrade::Remove-Unused-Dependencies "true";\n',
        "0644",
    ),
    (
        "/etc/ssh/sshd_config.d/10-pi-rack.conf",
        "# Drop-in, not an edit to sshd_config: drop-ins are the supported route on\n"
        "# Debian 13, and editing the main file means every future package upgrade\n"
        "# prompts about a modified conffile.\n"
        "#\n"
        "# cloud-init's ssh_pwauth already does most of this. It is repeated here so\n"
        "# the setting survives anything that re-runs and reconsiders cloud-init's\n"
        "# opinion, and so that `sshd -T` shows the intent in one readable place.\n"
        "PasswordAuthentication no\n"
        "KbdInteractiveAuthentication no\n"
        "PermitRootLogin no\n"
        "# fail2ban is deliberately NOT installed. With password auth off there is\n"
        "# nothing to brute-force, and a daemon that can firewall you out of a\n"
        "# headless board you can only reach over SSH is a net liability.\n",
        "0644",
    ),
    (
        "/etc/systemd/system/pi-rack-time-sync.conf.d-README",
        "# The Pi has no battery-backed clock. Rather than fit an RTC module to the\n"
        "# one board that can take one, order anything time-sensitive after the\n"
        "# clock is right:\n"
        "#\n"
        "#   systemctl enable systemd-time-wait-sync.service\n"
        "#   ... and in your unit:  After=time-sync.target\n"
        "#\n"
        "# That works on all five boards, costs nothing, and never needs a new cell.\n",
        "0644",
    ),
]
# Note: the node identity file (/etc/pi-rack.env) is contributed by roles.py, so
# that it is written from the same data the role scripts are given. There is
# deliberately only one identity file - two would drift.

BASE_RUNCMD: list[str] = [
    # Prove the seed actually ran. If this file is missing after a boot, cloud-init
    # did not execute - which is a completely different problem from "the service
    # failed", and knowing which saves an hour.
    "[ sh, -c, \"date -Is > /var/lib/pi-rack-provisioned\" ]",
]


def validate(text: str, what: str) -> None:
    """Parse the rendered YAML back. A silent syntax error here means a Pi that
    boots to a login prompt with no user, no network and no SSH - i.e. a node you
    have to physically retrieve. Worth the check."""
    if _yaml is None:
        return
    try:
        _yaml.safe_load(text)
    except Exception as exc:  # pragma: no cover
        raise BootConfigError(f"{what} is not valid YAML: {exc}") from exc


_DS_RE = re.compile(r"ds=nocloud[^\s]*")


def reconcile_cmdline(boot_dir: Path, iid: str) -> bool:
    """Make `cmdline.txt` agree with our meta-data, or get out of the way.

    Raspberry Pi Imager appends ` ds=nocloud;i=<its own id>` to cmdline.txt when
    it writes a cloud-init seed. A kernel-cmdline instance id **overrides** the
    one in meta-data, and that quietly breaks the most useful property of this
    wizard: edit fleet.toml, re-seed the card, and have cloud-init genuinely
    re-provision. With a stale `i=` still on the cmdline, cloud-init decides it
    has seen this instance before and skips first-boot setup - and you get a node
    that boots with none of your changes and no error anywhere.

    So: if the parameter is there, rewrite its id to ours. If it is absent, leave
    it absent - the image's own `datasource_list: [NoCloud, None]` with
    `seedfrom: file:///boot/firmware` already finds the seed without it.

    Returns True if the file was changed.

    `cmdline.txt` MUST stay a single line. The bootloader reads line one and
    silently ignores anything after it, so a stray newline here removes every
    parameter that follows - a failure with no error message at all.
    """
    path = Path(boot_dir) / "cmdline.txt"
    if not path.exists():
        return False

    raw = path.read_text(encoding="utf-8")
    line = raw.strip().splitlines()[0] if raw.strip() else ""
    if "ds=nocloud" not in line:
        return False

    new_line = _DS_RE.sub(f"ds=nocloud;i={iid}", line, count=1)
    new_line = " ".join(new_line.split())
    if new_line == line:
        return False

    path.write_text(new_line + "\n", encoding="utf-8", newline="\n")
    return True


def write_seed(
    boot_dir: Path,
    fleet: Fleet,
    node: Node,
    bundle: RoleBundle | None = None,
    *,
    plan_revision: str = "",
    package_upgrade: bool = False,
) -> list[Path]:
    """Write user-data, network-config and meta-data into a mounted bootfs.

    `boot_dir` must be the root of the FAT32 boot partition, i.e. the drive
    Windows mounted after the image was written. This function refuses to write
    anywhere that does not look like one, because pointing it at the wrong
    directory would scatter three files into a real filesystem.
    """
    boot_dir = Path(boot_dir)
    if not boot_dir.is_dir():
        raise BootConfigError(f"{boot_dir} is not a directory")
    if not (boot_dir / "config.txt").exists() or not (boot_dir / "cmdline.txt").exists():
        raise BootConfigError(
            f"{boot_dir} does not look like a Raspberry Pi boot partition "
            "(no config.txt / cmdline.txt). Refusing to write seed files there."
        )

    reconcile_cmdline(boot_dir, instance_id(node, plan_revision))

    rendered = {
        "meta-data": render_meta_data(node, plan_revision),
        "network-config": render_network_config(fleet, node),
        "user-data": render_user_data(
            fleet, node, bundle, package_upgrade=package_upgrade
        ),
    }
    for name, text in rendered.items():
        validate(text, name)

    written: list[Path] = []
    for name, text in rendered.items():
        target = boot_dir / name
        # newline="\n": these are read by a Linux boot process. CRLF in cmdline.txt
        # is a classic Pi failure and there is no reason to risk it here.
        target.write_text(text, encoding="utf-8", newline="\n")
        written.append(target)
    return written
