// 24-LED legend collar - Every pixel named
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 54.3926;
R_OUT = 84.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  lab(0.000, 79.668, 3.15, "BIN NIGHT", true);   // driven by the firmware
  lab(18.907, 70.563, 3.15, "1", false);
  lab(39.834, 68.994, 3.15, "2", false);
  lab(51.656, 51.656, 3.15, "3", false);
  lab(68.994, 39.834, 3.15, "4", false);
  lab(70.563, 18.907, 3.15, "5", false);
  lab(77.319, 0.000, 3.15, "GARAGE", true);   // driven by the firmware
  lab(70.563, -18.907, 3.15, "7", false);
  lab(68.994, -39.834, 3.15, "8", false);
  lab(51.656, -51.656, 3.15, "9", false);
  lab(39.834, -68.994, 3.15, "10", false);
  lab(18.907, -70.563, 3.15, "SAM", true);   // driven by the firmware
  lab(0.000, -79.668, 3.15, "LAURA", true);   // driven by the firmware
  lab(-18.907, -70.563, 3.15, "AMANDA", true);   // driven by the firmware
  lab(-39.834, -68.994, 3.15, "ZAC", true);   // driven by the firmware
  lab(-51.656, -51.656, 3.15, "15", false);
  lab(-68.994, -39.834, 3.15, "16", false);
  lab(-70.563, -18.907, 3.15, "17", false);
  lab(-75.366, -0.000, 3.15, "DRIVEWAY", true);   // driven by the firmware
  lab(-70.563, 18.907, 3.15, "19", false);
  lab(-68.994, 39.834, 3.15, "20", false);
  lab(-51.656, 51.656, 3.15, "21", false);
  lab(-39.834, 68.994, 3.15, "22", false);
  lab(-18.907, 70.563, 3.15, "23", false);
}

legend();
