// 60-LED legend collar - Hour numerals
// Generated by build_legend.py. Edit that, not this.
//
// Text is RAISED by TEXT_H above the plate, so it reads without
// paint. For a two-colour print, pause at PLATE_H and swap
// filament -- the text starts exactly at that height.
//
// Bore is body dia 240.00 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;   // collar thickness
TEXT_H  = 0.6;   // raised text, 3 layers at 0.2
TICK_H  = 0.4;
R_IN = 120.4000;
R_OUT = 154.4000;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// A label centred on `frac` of the dial, lying tangentially.
// 0 = 12 o'clock, increasing clockwise, matching P() in the
// firmware -- so a label lands on the pixel it describes.
// `flip` turns a bottom-half label the right way up: without it
// everything from 3 to 9 o'clock stands on its head.
module label(frac, r, size, txt, bold = true, flip = false) {
  a = frac * 360;
  rotate([0, 0, -a + (flip ? 180 : 0)])
    translate([0, flip ? -r : r, PLATE_H])
      linear_extrude(height = TEXT_H)
        text(txt, size = size, halign = "center",
             valign = "center", font = bold ?
             "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 59]) {
    a = i * 6.000000;
    major = (i % 5) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.5 : 0.2), R_OUT - 4.5, PLATE_H])
        cube([major ? 1.0 : 0.4, 3.0, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  label(0.083333, 141.480, 8.18, "1");
  label(0.166667, 141.480, 8.18, "2");
  label(0.250000, 141.480, 8.18, "3");
  label(0.333333, 141.480, 8.18, "4");
  label(0.416667, 141.480, 8.18, "5");
  label(0.500000, 141.480, 8.18, "6");
  label(0.583333, 141.480, 8.18, "7");
  label(0.666667, 141.480, 8.18, "8");
  label(0.750000, 141.480, 8.18, "9");
  label(0.833333, 141.480, 8.18, "10");
  label(0.916667, 141.480, 8.18, "11");
  label(1.000000, 141.480, 8.18, "12");
}

legend();
