// 60-LED legend collar - Hour numerals
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 240.00 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 120.4000;
R_OUT = 154.4000;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 59]) {
    a = i * 6.000000;
    major = (i % 5) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  lab(69.550, 120.464, 8.18, "1");
  lab(120.464, 69.550, 8.18, "2");
  lab(139.100, 0.000, 8.18, "3");
  lab(120.464, -69.550, 8.18, "4");
  lab(69.550, -120.464, 8.18, "5");
  lab(0.000, -139.100, 8.18, "6");
  lab(-69.550, -120.464, 8.18, "7");
  lab(-120.464, -69.550, 8.18, "8");
  lab(-139.100, -0.000, 8.18, "9");
  lab(-120.464, 69.550, 8.18, "10");
  lab(-69.550, 120.464, 8.18, "11");
  lab(-0.000, 139.100, 8.18, "12");
}

legend();
