// 24-LED legend collar - Ambient status
// Generated by build_legend.py. Edit that, not this.
//
// Text is RAISED by TEXT_H above the plate, so it reads without
// paint. For a two-colour print, pause at PLATE_H and swap
// filament -- the text starts exactly at that height.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;   // collar thickness
TEXT_H  = 0.6;   // raised text, 3 layers at 0.2
TICK_H  = 0.4;
R_IN = 54.3926;
R_OUT = 76.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// A label centred on `frac` of the dial, lying tangentially.
// 0 = 12 o'clock, increasing clockwise, matching P() in the
// firmware -- so a label lands on the pixel it describes.
// `flip` turns a bottom-half label the right way up: without it
// everything from 3 to 9 o'clock stands on its head.
module label(frac, r, size, txt, bold = true, flip = false) {
  a = frac * 360;
  rotate([0, 0, -a + (flip ? 180 : 0)])
    translate([0, flip ? -r : r, PLATE_H])
      linear_extrude(height = TEXT_H)
        text(txt, size = size, halign = "center",
             valign = "center", font = bold ?
             "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.5 : 0.2), R_OUT - 4.5, PLATE_H])
        cube([major ? 1.0 : 0.4, 3.0, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  // lit colour: #00961e
  label(0.000000, 68.033, 4.07, "BIN NIGHT", true, false);
  label(0.000000, 60.993, 2.53, "green waste / yellow recycling", false, false);
  rotate([0, 0, -0.0000]) translate([0, 73.313, PLATE_H])
    cylinder(h = TEXT_H, r = 1.21);
  // lit colour: #964600
  label(0.250000, 68.033, 4.07, "GARAGE OPEN", true, false);
  rotate([0, 0, -90.0000]) translate([0, 73.313, PLATE_H])
    cylinder(h = TEXT_H, r = 1.21);
  // lit colour: #002859
  label(0.500000, 68.033, 4.07, "WHO'S HOME", true, true);
  label(0.500000, 60.993, 2.53, "Sam  Laura  Amanda  Zac", false, true);
  rotate([0, 0, -180.0000]) translate([0, 73.313, PLATE_H])
    cylinder(h = TEXT_H, r = 1.21);
  // lit colour: #c80000
  label(0.750000, 68.033, 4.07, "DRIVEWAY", true, false);
  label(0.750000, 60.993, 2.53, "blinking = someone there", false, false);
  rotate([0, 0, -270.0000]) translate([0, 73.313, PLATE_H])
    cylinder(h = TEXT_H, r = 1.21);
}

legend();
