// 60-LED legend collar - Who is home
// Generated by build_legend.py. Edit that, not this.
//
// Text is RAISED by TEXT_H above the plate, so it reads without
// paint. For a two-colour print, pause at PLATE_H and swap
// filament -- the text starts exactly at that height.
//
// Bore is body dia 240.00 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;   // collar thickness
TEXT_H  = 0.6;   // raised text, 3 layers at 0.2
TICK_H  = 0.4;
R_IN = 120.4000;
R_OUT = 154.4000;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// A label centred on `frac` of the dial, lying tangentially.
// 0 = 12 o'clock, increasing clockwise, matching P() in the
// firmware -- so a label lands on the pixel it describes.
// `flip` turns a bottom-half label the right way up: without it
// everything from 3 to 9 o'clock stands on its head.
module label(frac, r, size, txt, bold = true, flip = false) {
  a = frac * 360;
  rotate([0, 0, -a + (flip ? 180 : 0)])
    translate([0, flip ? -r : r, PLATE_H])
      linear_extrude(height = TEXT_H)
        text(txt, size = size, halign = "center",
             valign = "center", font = bold ?
             "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 59]) {
    a = i * 6.000000;
    major = (i % 5) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.5 : 0.2), R_OUT - 4.5, PLATE_H])
        cube([major ? 1.0 : 0.4, 3.0, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  // lit colour: #002859
  label(0.453100, 141.480, 6.29, "SAM", true, true);
  rotate([0, 0, -163.1160]) translate([0, 149.640, PLATE_H])
    cylinder(h = TEXT_H, r = 1.87);
  // lit colour: #5a0046
  label(0.484400, 141.480, 6.29, "LAURA", true, true);
  rotate([0, 0, -174.3840]) translate([0, 149.640, PLATE_H])
    cylinder(h = TEXT_H, r = 1.87);
  // lit colour: #004628
  label(0.515600, 141.480, 6.29, "AMANDA", true, true);
  rotate([0, 0, -185.6160]) translate([0, 149.640, PLATE_H])
    cylinder(h = TEXT_H, r = 1.87);
  // lit colour: #463200
  label(0.546900, 141.480, 6.29, "ZAC", true, true);
  rotate([0, 0, -196.8840]) translate([0, 149.640, PLATE_H])
    cylinder(h = TEXT_H, r = 1.87);
}

legend();
