// 24-LED legend collar - Blank
// Generated by build_legend.py. Edit that, not this.
//
// Text is RAISED by TEXT_H above the plate, so it reads without
// paint. For a two-colour print, pause at PLATE_H and swap
// filament -- the text starts exactly at that height.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;   // collar thickness
TEXT_H  = 0.6;   // raised text, 3 layers at 0.2
TICK_H  = 0.4;
R_IN = 54.3926;
R_OUT = 76.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// A label centred on `frac` of the dial, lying tangentially.
// 0 = 12 o'clock, increasing clockwise, matching P() in the
// firmware -- so a label lands on the pixel it describes.
// `flip` turns a bottom-half label the right way up: without it
// everything from 3 to 9 o'clock stands on its head.
module label(frac, r, size, txt, bold = true, flip = false) {
  a = frac * 360;
  rotate([0, 0, -a + (flip ? 180 : 0)])
    translate([0, flip ? -r : r, PLATE_H])
      linear_extrude(height = TEXT_H)
        text(txt, size = size, halign = "center",
             valign = "center", font = bold ?
             "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.5 : 0.2), R_OUT - 4.5, PLATE_H])
        cube([major ? 1.0 : 0.4, 3.0, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
}

legend();
