// 60-LED legend collar - Every pixel named
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 240.00 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 120.4000;
R_OUT = 160.4000;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 59]) {
    a = i * 6.000000;
    major = (i % 5) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  lab(0.000, 155.000, 3.60, "BIN NIGHT", true);   // driven by the firmware
  lab(15.412, 146.632, 3.60, "1", false);
  lab(32.226, 151.613, 3.60, "2", false);
  lab(45.561, 140.224, 3.60, "3", false);
  lab(63.044, 141.600, 3.60, "4", false);
  lab(73.720, 127.687, 3.60, "5", false);
  lab(91.107, 125.398, 3.60, "6", false);
  lab(98.657, 109.569, 3.60, "7", false);
  lab(115.187, 103.715, 3.60, "8", false);
  lab(119.281, 86.663, 3.60, "9", false);
  lab(134.234, 77.500, 3.60, "10", false);
  lab(134.693, 59.969, 3.60, "11", false);
  lab(147.414, 47.898, 3.60, "12", false);
  lab(144.218, 30.654, 3.60, "13", false);
  lab(154.151, 16.202, 3.60, "14", false);
  lab(147.440, 0.000, 3.60, "GARAGE", true);   // driven by the firmware
  lab(154.151, -16.202, 3.60, "16", false);
  lab(144.218, -30.654, 3.60, "17", false);
  lab(147.414, -47.898, 3.60, "18", false);
  lab(134.693, -59.969, 3.60, "19", false);
  lab(134.234, -77.500, 3.60, "20", false);
  lab(119.281, -86.663, 3.60, "21", false);
  lab(115.187, -103.715, 3.60, "22", false);
  lab(98.657, -109.569, 3.60, "23", false);
  lab(91.107, -125.398, 3.60, "24", false);
  lab(73.720, -127.687, 3.60, "25", false);
  lab(63.044, -141.600, 3.60, "26", false);
  lab(45.561, -140.224, 3.60, "27", false);
  lab(32.226, -151.613, 3.60, "28", false);
  lab(15.412, -146.632, 3.60, "SAM", true);   // driven by the firmware
  lab(0.000, -155.000, 3.60, "LAURA", true);   // driven by the firmware
  lab(-15.412, -146.632, 3.60, "AMANDA", true);   // driven by the firmware
  lab(-32.226, -151.613, 3.60, "ZAC", true);   // driven by the firmware
  lab(-45.561, -140.224, 3.60, "33", false);
  lab(-63.044, -141.600, 3.60, "34", false);
  lab(-73.720, -127.687, 3.60, "35", false);
  lab(-91.107, -125.398, 3.60, "36", false);
  lab(-98.657, -109.569, 3.60, "37", false);
  lab(-115.187, -103.715, 3.60, "38", false);
  lab(-119.281, -86.663, 3.60, "39", false);
  lab(-134.234, -77.500, 3.60, "40", false);
  lab(-134.693, -59.969, 3.60, "41", false);
  lab(-147.414, -47.898, 3.60, "42", false);
  lab(-144.218, -30.654, 3.60, "43", false);
  lab(-154.151, -16.202, 3.60, "44", false);
  lab(-147.440, -0.000, 3.60, "DRIVEWAY", true);   // driven by the firmware
  lab(-154.151, 16.202, 3.60, "46", false);
  lab(-144.218, 30.654, 3.60, "47", false);
  lab(-147.414, 47.898, 3.60, "48", false);
  lab(-134.693, 59.969, 3.60, "49", false);
  lab(-134.234, 77.500, 3.60, "50", false);
  lab(-119.281, 86.663, 3.60, "51", false);
  lab(-115.187, 103.715, 3.60, "52", false);
  lab(-98.657, 109.569, 3.60, "53", false);
  lab(-91.107, 125.398, 3.60, "54", false);
  lab(-73.720, 127.687, 3.60, "55", false);
  lab(-63.044, 141.600, 3.60, "56", false);
  lab(-45.561, 140.224, 3.60, "57", false);
  lab(-32.226, 151.613, 3.60, "58", false);
  lab(-15.412, 146.632, 3.60, "59", false);
}

legend();
