// 24-LED legend collar - Ambient status
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 54.3926;
R_OUT = 76.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  // lit colour #00961e
  lab(0.000, 68.033, 4.07, "BIN NIGHT");
  lab(0.000, 61.521, 2.53, "green / yellow", false);
  // lit colour #964600
  lab(61.286, 0.000, 4.07, "GARAGE OPEN");
  // lit colour #002859
  lab(0.000, -68.033, 4.07, "WHO'S HOME");
  lab(0.000, -61.521, 2.53, "Sam Laura Amanda Zac", false);
  // lit colour #c80000
  lab(-65.071, -0.000, 4.07, "DRIVEWAY");
  lab(-61.853, -0.000, 2.53, "blinking", false);
}

legend();
