// 60-LED legend collar - Ambient status
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 240.00 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 120.4000;
R_OUT = 154.4000;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 59]) {
    a = i * 6.000000;
    major = (i % 5) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  // lit colour #00961e
  lab(0.000, 141.480, 6.29, "BIN NIGHT");
  lab(0.000, 131.416, 3.91, "green / yellow", false);
  // lit colour #964600
  lab(131.719, 0.000, 6.29, "GARAGE OPEN");
  // lit colour #002859
  lab(0.000, -141.480, 6.29, "WHO'S HOME");
  lab(0.000, -131.416, 3.91, "Sam Laura Amanda Zac", false);
  // lit colour #c80000
  lab(-137.569, -0.000, 6.29, "DRIVEWAY");
  lab(-131.281, -0.000, 3.91, "blinking", false);
}

legend();
