// 24-LED legend collar - Who is home
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 54.3926;
R_OUT = 76.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  // lit colour #002859
  lab(19.759, -65.100, 4.07, "SAM");
  // lit colour #5a0046
  lab(6.658, -67.706, 4.07, "LAURA");
  // lit colour #004628
  lab(-6.658, -67.706, 4.07, "AMANDA");
  // lit colour #463200
  lab(-19.759, -65.100, 4.07, "ZAC");
}

legend();
