// 24-LED legend collar - Hour numerals
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 107.99 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 54.3926;
R_OUT = 76.3926;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 23]) {
    a = i * 15.000000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  lab(33.246, 57.584, 5.29, "1");
  lab(57.584, 33.246, 5.29, "2");
  lab(66.493, 0.000, 5.29, "3");
  lab(57.584, -33.246, 5.29, "4");
  lab(33.246, -57.584, 5.29, "5");
  lab(0.000, -66.493, 5.29, "6");
  lab(-33.246, -57.584, 5.29, "7");
  lab(-57.584, -33.246, 5.29, "8");
  lab(-66.493, -0.000, 5.29, "9");
  lab(-57.584, 33.246, 5.29, "10");
  lab(-33.246, 57.584, 5.29, "11");
  lab(-0.000, 66.493, 5.29, "12");
}

legend();
