// 32-LED legend collar - Every pixel named
// Generated by build_legend.py. Edit that, not this.
//
// Every label is UPRIGHT - no rotation - so the collar reads
// from across the room whichever pixel you are looking at.
//
// Text is RAISED by TEXT_H. For a two-colour print, pause at
// PLATE_H and swap filament: the text starts exactly there.
//
// Bore is body dia 119.85 + 0.40 clearance.
$fn = 160;
PLATE_H = 2.4;
TEXT_H = 0.6;
TICK_H = 0.4;
R_IN = 60.3250;
R_OUT = 94.3250;

module plate() {
  difference() {
    cylinder(h = PLATE_H, r = R_OUT);
    translate([0, 0, -1]) cylinder(h = PLATE_H + 2, r = R_IN);
  }
}

// Upright: translate only, never rotate.
module lab(x, y, size, txt, bold = true) {
  translate([x, y, PLATE_H])
    linear_extrude(height = TEXT_H)
      text(txt, size = size, halign = "center",
           valign = "center", font = bold ?
           "DejaVu Sans:style=Bold" : "DejaVu Sans");
}

module ticks() {
  for (i = [0 : 31]) {
    a = i * 11.250000;
    major = (i % 2) == 0;
    rotate([0, 0, -a])
      translate([-(major ? 0.45 : 0.18), R_OUT - 3.6, PLATE_H])
        cube([major ? 0.9 : 0.36, 2.4, TICK_H]);
  }
}

module legend() {
  plate();
  ticks();
  lab(0.000, 88.970, 3.57, "BIN NIGHT", true);   // driven by the firmware
  lab(15.895, 79.908, 3.57, "1", false);
  lab(34.047, 82.198, 3.57, "2", false);
  lab(45.264, 67.742, 3.57, "3", false);
  lab(62.911, 62.911, 3.57, "4", false);
  lab(67.742, 45.264, 3.57, "5", false);
  lab(82.198, 34.047, 3.57, "6", false);
  lab(79.908, 15.895, 3.57, "7", false);
  lab(86.468, 0.000, 3.57, "GARAGE", true);   // driven by the firmware
  lab(79.908, -15.895, 3.57, "9", false);
  lab(82.198, -34.047, 3.57, "10", false);
  lab(67.742, -45.264, 3.57, "11", false);
  lab(62.911, -62.911, 3.57, "12", false);
  lab(45.264, -67.742, 3.57, "13", false);
  lab(34.047, -82.198, 3.57, "14", false);
  lab(15.895, -79.908, 3.57, "SAM", true);   // driven by the firmware
  lab(0.000, -88.970, 3.57, "LAURA", true);   // driven by the firmware
  lab(-15.895, -79.908, 3.57, "AMANDA", true);   // driven by the firmware
  lab(-34.047, -82.198, 3.57, "ZAC", true);   // driven by the firmware
  lab(-45.264, -67.742, 3.57, "19", false);
  lab(-62.911, -62.911, 3.57, "20", false);
  lab(-67.742, -45.264, 3.57, "21", false);
  lab(-82.198, -34.047, 3.57, "22", false);
  lab(-79.908, -15.895, 3.57, "23", false);
  lab(-84.254, -0.000, 3.57, "DRIVEWAY", true);   // driven by the firmware
  lab(-79.908, 15.895, 3.57, "25", false);
  lab(-82.198, 34.047, 3.57, "26", false);
  lab(-67.742, 45.264, 3.57, "27", false);
  lab(-62.911, 62.911, 3.57, "28", false);
  lab(-45.264, 67.742, 3.57, "29", false);
  lab(-34.047, 82.198, 3.57, "30", false);
  lab(-15.895, 79.908, 3.57, "31", false);
}

legend();
